spring.application.name=api-gateway
server.port=8751

eureka.client.service-url.defaultZone=http://localhost:8750/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info,metrics,gateway

spring.security.user.name=admin
spring.security.user.password=nimda
management.endpoint.health.show-details=when-authorized
