spring.application.name=product-service
server.port=8753

eureka.client.service-url.defaultZone=http://localhost:8750/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

spring.datasource.url=jdbc:postgresql://localhost:5432/user_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info,metrics

logging.level.org.springframework=INFO
logging.level.com.darkharsus=DEBUG
logging.level.com.netflix.discovery=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
